Update patch set 2
Patch Set 2:

> Patch Set 2:
> 
> Legit build failure, we are using a hidden method outside of the libray.
> 
> Caused by: org.gradle.api.GradleException: Lint found errors in the project; aborting build.
> 
> Fix the issues identified by lint, or add the following to your build script to proceed with errors:
> ...
> android {
> lintOptions {
> abortOnError false
> }
> }
> ...
> 
> The first 3 errors (out of 14) were:
> /usr/local/google/buildbot/src/android/androidx-master-dev/frameworks/support/webkit/integration-tests/testapp/src/main/java/com/example/androidx/webkit/AssetLoaderAjaxActivity.java:47: Error: WebViewAssetLoader.shouldInterceptRequest can only be called from within the same library (webkit) [RestrictedApi]
> return mAssetLoader.shouldInterceptRequest(request);
> ~~~~~~~~~~~~~~~~~~~~~~
> /usr/local/google/buildbot/src/android/androidx-master-dev/frameworks/support/webkit/integration-tests/testapp/src/main/java/com/example/androidx/webkit/AssetLoaderAjaxActivity.java:52: Error: WebViewAssetLoader.shouldInterceptRequest can only be called from within the same library (webkit) [RestrictedApi]
> return mAssetLoader.shouldInterceptRequest(request);
> ~~~~~~~~~~~~~~~~~~~~~~
> /usr/local/google/buildbot/src/android/androidx-master-dev/frameworks/support/webkit/integration-tests/testapp/src/main/java/com/example/androidx/webkit/AssetLoaderAjaxActivity.java:67: Error: WebViewAssetLoader can only be called from within the same library (webkit) [RestrictedApi]
> mAssetLoader = new WebViewAssetLoader(this);
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Oh, that is indeed a case we'd like to support. We want to be able to use soon-to-be-unhidden APIs in our test app. This gives our team a chance to see the API in action (so we can address obvious usability issues), before exposing to the world.

^ In that case, maybe LIBRARY_GROUP is the right thing for us? Or could you recommend another @RestrictTo value?

Patch-set: 2
Reviewer: Gerrit User 1141809 <1141809@85c56323-6fa9-3386-8a01-6480fb634889>