Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> LGTM, some general questions
> 
> - is this for the Java or Kotlin version of the reference docs?
> - If this is for Kotlin, is the target 'dac-as-kotlin' available?

Hmm when I try outputFormat = "dac-as-kotlin", it fails, saying:

  org.jetbrains.dokka.Utilities.ServiceLookupException: No implementation with name dac-as-kotlin found in category format


I think that both formats document all of the kotlin and java APIs, just that the "dac" format documents Kotlin files for usage in Kotlin whereas the "dac-as-java" format documents Kotlin files for usage in Java, and so for example explicitly calls out Companion objects instead of documenting their fields inline.

Also slightly related, it turned out that I was seeing some nondeterminism problems with format "dac-as-java" but they went away with the "dac" format so thanks for that

Patch-set: 1
Reviewer: Gerrit User 1137668 <1137668@85c56323-6fa9-3386-8a01-6480fb634889>