Update patch set 1
Patch Set 1:

PreferenceGroupTest is currently failing due to:

java.lang.IllegalAccessError: Method 'boolean[] androidx.preference.PreferenceGroupKt.$jacocoInit()' is inaccessible to class 'androidx.preference.PreferenceGroupTest' (declaration of 'androidx.preference.PreferenceGroupTest' appears in /data/app/androidx.preference.ktx.test-vUf44BJTcaRjrkQ1Y5ssHg==/base.apk)

I noticed most of ktx has this in build.gradle, does this fix this error?

Patch-set: 1
Reviewer: Gerrit User 1232209 <1232209@85c56323-6fa9-3386-8a01-6480fb634889>
Reviewer: Gerrit User 1343300 <1343300@85c56323-6fa9-3386-8a01-6480fb634889>