Update patch set 3
Patch Set 3:

NightModeLateSuperOnCreateTestCase is unexpectedly failing (in that it's successfully setting night mode) on test devices. We'll need to look into this before merging.

java.lang.AssertionError: expected:<16> but was:<32>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at androidx.appcompat.testutils.NightModeUtils.assertConfigurationNightModeEquals(NightModeUtils.java:56)
	at androidx.appcompat.app.NightModeLateSuperOnCreateTestCase.testActivityRecreate(NightModeLateSuperOnCreateTestCase.java:67)

Patch-set: 3
Reviewer: Gerrit User 1044446 <1044446@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Presubmit-Ready=0