Update patch set 5
Patch Set 5:

Thanks for the review!
I have an additional change in the build.gradle.
Change from
testCompleOnly(project(":camera:camera-extensions-stub"))
to
testImplementation(project(":camera:camera-extensions-stub"))

this is because the local test environment is a little bit different from the presubmit environment.
My local test works find by using the testCompileOnly.
But the presubmit test might fail with the error
java.lang.TypeNotPresentException: Type androidx.camera.extensions.impl.ExtensionVersionImpl not present

To use the testImplementation can works fine in presubmit env.
If you have any concern about the build.gradle change, please let me know.

Thanks~

Patch-set: 5
Reviewer: Gerrit User 1475857 <1475857@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Presubmit-Ready=0