Update patch set 1
Patch Set 1:

This is the kind of crash I get in the app. The class ColumnView is in there, is a Parcelable and is stored with Bundle.writeParcelableArray() in the saved instande Bundle. Once the other setClassLoader() is added, everything is fine.

android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.levelup.touiteur.ColumnView
	at android.os.Parcel.readParcelable(Parcel.java:1958)
	at android.os.Parcel.readValue(Parcel.java:1846)
	at android.os.Parcel.readListInternal(Parcel.java:2092)
	at android.os.Parcel.readArrayList(Parcel.java:1536)
	at android.os.Parcel.readValue(Parcel.java:1867)
	at android.os.Parcel.readMapInternal(Parcel.java:2083)
	at android.os.Bundle.unparcel(Bundle.java:208)
	at android.os.Bundle.getSparseParcelableArray(Bundle.java:1167)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:806)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1083)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:635)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1431)
	at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:431)
	at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:160)
	at com.levelup.touiteur.AdapterFragmentColumn.finishUpdate(AdapterFragmentColumn.java:246)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:895)
	at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:469)
	at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:441)
	at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:422)
	at com.viewpagerindicator.TabPageIndicator$1.onClick(TabPageIndicator.java:44)
	at android.view.View.performClick(View.java:2552)
	at android.view.View$PerformClick.run(View.java:9229)
	at android.os.Handler.handleCallback(Handler.java:587)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:130)
	at android.app.ActivityThread.main(ActivityThread.java:3701)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:507)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:624)
	at dalvik.system.NativeStart.main(Native Method)

Patch-set: 1