Update patch set 4
Patch Set 4:

Hmm, now that checkApi is running, it's failing (even though I did run `./gradlew updateApi`).

One error is:

> Task :annotation:checkApi FAILED

/usr/local/google/workspace/aosp-androidx/frameworks/support/annotations/src/main/java/androidx/annotation/RestrictTo.java:71: error: Enum constant androidx.annotation.RestrictTo.Scope.GROUP_ID has changed deprecation state false --> true [ChangedDeprecated]
Aborting: Found compatibility problems checking the public API against the API in /usr/local/google/workspace/aosp-androidx/frameworks/support/annotations/api/1.0.0.txt


I would've thought that the text:

"public static enum RestrictTo.Scope {
    enum_constant @Deprecated public static final androidx.annotation.RestrictTo.Scope! GROUP_ID;
"

in annotations/api/1.0.0.txt would've caused Metalava to consider the previous deprecation state to also be "true". I guess I'll look closer into what's going on on Monday, maybe opening a bug with more details

Patch-set: 4
Reviewer: Gerrit User 1137668 <1137668@85c56323-6fa9-3386-8a01-6480fb634889>