Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> > Patch Set 1:
> > 
> > nick, sergey; any reason why this would fail?
> > it works fine on the paging branch checkout.
> > the only difference is the LibraryVersions change that is not included in this CL since master is further ahead.
> > these are the errors i receive:
> > /home/yboyar/src/androidx-master-dev/frameworks/support/paging/common/api/2.1.0-rc01.txt:24: error: Removed constructor androidx.paging.ItemKeyedDataSource() [RemovedMethod]
> > /home/yboyar/src/androidx-master-dev/frameworks/support/paging/common/api/2.1.0-rc01.txt:57: error: Removed constructor androidx.paging.PageKeyedDataSource() [RemovedMethod]
> > /home/yboyar/src/androidx-master-dev/frameworks/support/paging/common/src/main/java/androidx/paging/PagedList.java:621: error: Attempted to change method return from @NonNull to @Nullable: incompatible change for method androidx.paging.PagedList.get(int) [InvalidNullConversion]
> > /home/yboyar/src/androidx-master-dev/frameworks/support/paging/common/src/main/java/androidx/paging/PagedList.java:855: error: Attempted to change method return from @NonNull to @Nullable: incompatible change for method androidx.paging.PagedList.getLastKey() [InvalidNullConversion]
> > /home/yboyar/src/androidx-master-dev/frameworks/support/paging/common/api/2.1.0-rc01.txt:149: error: Removed constructor androidx.paging.PositionalDataSource() [RemovedMethod]
> > Aborting: Found compatibility problems checking the public API against the API in /home/yboyar/src/androidx-master-dev/frameworks/support/paging/common/api/2.1.0-rc01.txt
> > 
> > 
> > thereare some diffs between beta01 and rc01 though which i do not expect. will investigate.
> 
> Yeah, weird I don't see where @NonNull getLastKey(), it looks like it was always nullable

seems like the error is coming from beta01, any chance we mis-generated the API file there? i didn't change any code between these releases unless i did something wrong w/ 

➜  support git:(paging-2.1-rc01) ✗ cat paging/common/api/2.1.0-beta01.txt|grep ItemKeyedDataSource|grep ctor
    ctor public ItemKeyedDataSource.LoadCallback();
    ctor public ItemKeyedDataSource.LoadInitialCallback();
    ctor public ItemKeyedDataSource.LoadInitialParams(Key?, int, boolean);
    ctor public ItemKeyedDataSource.LoadParams(Key, int);
➜  support git:(paging-2.1-rc01) ✗ cat paging/common/api/2.1.0-rc01.txt|grep ItemKeyedDataSource|grep ctor
    ctor public ItemKeyedDataSource();
    ctor public ItemKeyedDataSource.LoadCallback();
    ctor public ItemKeyedDataSource.LoadInitialCallback();
    ctor public ItemKeyedDataSource.LoadInitialParams(Key, int, boolean);
    ctor public ItemKeyedDataSource.LoadParams(Key, int);


If I run the same commands on the paging release branch, it is actually there:
➜  support git:(paging-rc-01) cat paging/common/api/2.1.0-beta01.txt|grep ItemKeyedDataSource|grep ctor
    ctor public ItemKeyedDataSource();
    ctor public ItemKeyedDataSource.LoadCallback();
    ctor public ItemKeyedDataSource.LoadInitialCallback();
    ctor public ItemKeyedDataSource.LoadInitialParams(Key, int, boolean);
    ctor public ItemKeyedDataSource.LoadParams(Key, int);
➜  support git:(paging-rc-01) cat paging/common/api/2.1.0-rc01.txt|grep ItemKeyedDataSource|grep ctor
    ctor public ItemKeyedDataSource();
    ctor public ItemKeyedDataSource.LoadCallback();
    ctor public ItemKeyedDataSource.LoadInitialCallback();
    ctor public ItemKeyedDataSource.LoadInitialParams(Key, int, boolean);
    ctor public ItemKeyedDataSource.LoadParams(Key, int);
➜  support git:(paging-rc-01) 

so looks like we have different api files in release branch and master? might happen since the release branch probably uses an older version of this API file generator.

cc'in alan and jeff for directions.

Patch-set: 1
Reviewer: Gerrit User 1060337 <1060337@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Presubmit-Ready=0