Move alpha libraries to target Java 8.
Add a check so that any library that moves to alpha
has to move to Java 8 as well.

Also add a workaround to WorkManagerImplTest that is hit when moving
to Java 8:
/work/workmanager/src/androidTest/java/androidx/work/impl/WorkManagerImplTest.java:1387: error: reference to Preferences is ambiguous
        Preferences preferences = new Preferences(ApplicationProvider.getApplicationContext());
                                  ^
  both constructor Preferences(Context) in Preferences and constructor Preferences(SharedPreferences) in Preferences match

Test: ./gradlew buildOnServer
Change-Id: I1285b4ce12047511c98f44d58e13fac3aac9b0ad