Update patch set 1
Patch Set 1:

Hitting a reflection exceptions, which I assume is caused by AndroidX not having access to the updated chromium APK. However, if that's the case, I'm a bit surpised that the feature check passes...


java.lang.RuntimeException: Reflection failed for method public abstract void org.chromium.support_lib_boundary.WebSettingsBoundaryInterface.setWillSuppressErrorPage(boolean)
at org.chromium.support_lib_boundary.util.BoundaryInterfaceReflectionUtil$InvocationHandlerWithDelegateGetter.invoke(BoundaryInterfaceReflectionUtil.java:123)
at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
at $Proxy8.setWillSuppressErrorPage(Unknown Source)
at androidx.webkit.internal.WebSettingsAdapter.setWillSuppressErrorPage(WebSettingsAdapter.java:79)
at androidx.webkit.WebSettingsCompat.setWillSuppressErrorPage(WebSettingsCompat.java:245)
at androidx.webkit.WebSettingsCompatTest.testSuppressedErrorPage(WebSettingsCompatTest.java:110)
at java.lang.reflect.Method.invoke(Native Method)
 ...

Patch-set: 1
Reviewer: Gerrit User 1101490 <1101490@85c56323-6fa9-3386-8a01-6480fb634889>
Reviewer: Gerrit User 1316328 <1316328@85c56323-6fa9-3386-8a01-6480fb634889>