DO NOT MERGE - Fix NoClassDefFoundError caused by CallbackToFutureAdapter
Test: ./gradlew camera:camera-camera2:connectedAndroidTest
Change-Id: I3af94a50ff6bc34516a36bb8b7d6691b2516072e