Create patch set 2
Patch Set 2: Commit message was updated.

Patch-set: 2
Patch-set-description: Edit commit message
Subject: Fix ATP timeout due to NoClassDefFoundError which is caused by CallbackToFutureAdapter class not found.
Commit: 06475a4d3227dd1348a07350ac643ce5ea5cd6ee
Tag: autogenerated:gerrit:newPatchSet
Groups: 33b2ce8dff3ba48ad4651bc8f876c446534fbbbd