Create change
Uploaded patch set 1.

Patch-set: 1
Change-id: I3af94a50ff6bc34516a36bb8b7d6691b2516072e
Subject: Fix NoClassDefFoundError caused by CallbackToFutureAdapter
Branch: refs/heads/androidx-master-dev
Status: new
Topic: 
Commit: 4bb9079ff9e263add49f2c43b874ca5be4ddfc9f
Tag: autogenerated:gerrit:newPatchSet
Groups: 4bb9079ff9e263add49f2c43b874ca5be4ddfc9f
Private: false
Work-in-progress: false