Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> > Patch Set 1:
> > 
> > > Patch Set 1:
> > > 
> > > Jeff, Alan; any advice here?
> > > Chris is OOO and I'm trying to ship paging so I'm a little bit lost on history here.
> > 
> > Alan is OOO too :(
> > 
> > Hmm. It looks like for some reason the relevant output isn't showing up in build_error.log but it is showing up in build.log :
> > 
> > androidx-master-dev/frameworks/support/paging/common/api/2.1.0-rc01.txt:24: error: Removed constructor androidx.paging.ItemKeyedDataSource() [RemovedMethod:9]
> > androidx-master-dev/frameworks/support/paging/common/api/2.1.0-rc01.txt:57: error: Removed constructor androidx.paging.PageKeyedDataSource() [RemovedMethod:9]
> > Aborting: Found compatibility problems checking the public API against the API in androidx-master-dev/frameworks/support/paging/common/api/2.1.0-rc01.txt
> > androidx-master-dev/frameworks/support/paging/common/src/main/java/androidx/paging/PagedList.java:621: error: Attempted to change method return from @NonNull to @Nullable: incompatible change for method androidx.paging.PagedList.get(int) [InvalidNullConversion:135]
> > androidx-master-dev/frameworks/support/paging/common/src/main/java/androidx/paging/PagedList.java:855: error: Attempted to change method return from @NonNull to @Nullable: incompatible change for method androidx.paging.PagedList.getLastKey() [InvalidNullConversion:135]
> > androidx-master-dev/frameworks/support/paging/common/api/2.1.0-rc01.txt:149: error: Removed constructor androidx.paging.PositionalDataSource() [RemovedMethod:9]
> 
> where is it coming from though? beta01 and rc01 are supposed to be the same. by any chance, may it be comparing to tip of tree which already moved to 2.2 ?


It turns out that in the paging release checkout in the file ./buildSrc/src/main/kotlin/androidx/build/SupportLibraryExtension.kt , the default value of useMetalava is false, whereas is androidx-master-dev, the value is true.

You may be able to enable metalava there (see aosp/785023 ), or if that's inconvenient it should be possible to set `useMetalava = true` in just the relevant project(s).

Patch-set: 1