Update patch set 2
Patch Set 2:

> Patch Set 2:
> 
> > Patch Set 2:
> > 
> > > Patch Set 2:
> > > 
> > > We think these failures may be related to a bug in metalava.  I've asked Jeff to take a look tomorrow EST (Wednesday)
> > 
> > Hmm I thought that this looked like b/131372502 but after some more investigation (`mv media media1`, fix some build.gradle's, `./gradlew :media2:media2-widget:lintDebug`), it looks like it might not be.
> > 
> > When I do that I still some errors that look like:
> > 
> > /usr/local/google/buildbot/src/android/androidx-master-dev/frameworks/support/media2/widget/src/main/java/androidx/media2/widget/MediaControlView.java:1721: Error: TrackInfo.getTrackType can only be called from within the same library group (groupId=androidx.media2) [RestrictedApi]
> > int trackType = trackInfos.get(i).getTrackType();
> > 
> > 
> > I'll take a closer look in a bit.
> 
> Hmm I've started investigating and so far it seems that lint is correctly identifying the containing project as frameworks/support/media2/widget but for some reason is treating the groupId of that project as null

media2-widget has been changed its module name and group (androidx.media2) from media-widget and androidx.media since alpha-07. Would it be related somehow? (FYI, PublishDocsRules.kt is also outdated. It shouldn't affect lint errors, though..)

Patch-set: 2
Reviewer: Gerrit User 1018419 <1018419@85c56323-6fa9-3386-8a01-6480fb634889>