Update patch set 2
Patch Set 2:

> Patch Set 2:
> 
> > Patch Set 2:
> > 
> > > Patch Set 2:
> > > 
> > > > Patch Set 2:
> > > > 
> > > > (1 comment)
> > > 
> > > I think it has to do with this CL in the relation chain (https://android-review.googlesource.com/c/platform/frameworks/support/+/904535) which has work's trackRestrictedAPIs = false.
> > 
> > Well... why is those things?  https://imgur.com/gallery/7qNl90o
> 
> https://android-review.googlesource.com/c/platform/frameworks/support/+/904535/2//COMMIT_MSG#17
> 
> In the case of workmanager, the errors messages that Metalava displays are:
> 
> 
> frameworks/support/work/workmanager/src/main/java/androidx/work/impl/WorkDatabase.java:145: error: Class androidx.work.impl.model.WorkSpecDao is hidden but was referenced (as return type) from public method androidx.work.impl.WorkDatabase.workSpecDao() [ReferencesHidden]
> frameworks/support/work/workmanager/src/main/java/androidx/work/impl/WorkDatabase.java:150: error: Class androidx.work.impl.model.DependencyDao is hidden but was referenced (as return type) from public method androidx.work.impl.WorkDatabase.dependencyDao() [ReferencesHidden]
> frameworks/support/work/workmanager/src/main/java/androidx/work/impl/WorkDatabase.java:155: error: Class androidx.work.impl.model.WorkTagDao is hidden but was referenced (as return type) from public method androidx.work.impl.WorkDatabase.workTagDao() [ReferencesHidden]
> frameworks/support/work/workmanager/src/main/java/androidx/work/impl/WorkDatabase.java:160: error: Class androidx.work.impl.model.SystemIdInfoDao is hidden but was referenced (as return type) from public method androidx.work.impl.WorkDatabase.systemIdInfoDao() [ReferencesHidden]
> frameworks/support/work/workmanager/src/main/java/androidx/work/impl/WorkDatabase.java:165: error: Class androidx.work.impl.model.WorkNameDao is hidden but was referenced (as return type) from public method androidx.work.impl.WorkDatabase.workNameDao() [ReferencesHidden]
> frameworks/support/work/workmanager/src/main/java/androidx/work/impl/background/greedy/GreedyScheduler.java:64: error: Class androidx.work.impl.constraints.WorkConstraintsTracker is hidden but was referenced (as parameter type) from public parameter workConstraintsTracker in androidx.work.impl.background.greedy.GreedyScheduler(androidx.work.impl.WorkManagerImpl workManagerImpl, androidx.work.impl.constraints.WorkConstraintsTracker workConstraintsTracker) [ReferencesHidden]
> frameworks/support/work/workmanager/src/main/java/androidx/work/impl/background/systemjob/SystemJobScheduler.java:67: error: Class androidx.work.impl.background.systemjob.SystemJobInfoConverter is not public but was referenced (as parameter type) from public parameter systemJobInfoConverter in androidx.work.impl.background.systemjob.SystemJobScheduler(android.content.Context context, androidx.work.impl.WorkManagerImpl workManager, android.app.job.JobScheduler jobScheduler, androidx.work.impl.background.systemjob.SystemJobInfoConverter systemJobInfoConverter) [ReferencesHidden]
> frameworks/support/work/workmanager/src/main/java/androidx/work/impl/constraints/trackers/ConstraintTracker.java:56: error: Class androidx.work.impl.constraints.ConstraintListener is hidden but was referenced (as parameter type) from public parameter listener in androidx.work.impl.constraints.trackers.ConstraintTracker.addListener(androidx.work.impl.constraints.ConstraintListener<T> listener) [ReferencesHidden]
> frameworks/support/work/workmanager/src/main/java/androidx/work/impl/constraints/trackers/ConstraintTracker.java:76: error: Class androidx.work.impl.constraints.ConstraintListener is hidden but was referenced (as parameter type) from public parameter listener in androidx.work.impl.constraints.trackers.ConstraintTracker.removeListener(androidx.work.impl.constraints.ConstraintListener<T> listener) [ReferencesHidden]esources
> frameworks/support/work/workmanager/src/main/java/androidx/work/impl/constraints/trackers/NetworkStateTracker.java:75: error: Class androidx.work.impl.constraints.NetworkState is hidden but was referenced (as return type) from public method androidx.work.impl.constraints.trackers.NetworkStateTracker.getInitialState() [ReferencesHidden]
> 
> 
> I'm still planning on opening some bugs for these kinds of things but haven't yet done that

Looking at the first one... WorkDatabase is *also* a hidden/RestrictTo class.  So the fact that it has a public method referencing a hidden/RestrictTo thing should be totally fine, right?

Patch-set: 2