Update patch set 1
Patch Set 1:

1) Changed media2-widget's build.gradle in aosp/987492 and so need to resolve merge conflicts
2) For the treehuger failure: There are lots of lint errors with "RestrictedApi" things. 

/usr/local/google/home/insun/repos/androidx-dev/frameworks/support/media2/widget/src/main/java/androidx/media2/widget/MediaControlView.java:1721: Error: TrackInfo.getTrackType can only be called from within the same library group (groupId=androidx.media2) [RestrictedApi]
            int trackType = trackInfos.get(i).getTrackType();
                                              ~~~~~~~~~~~~

Although they (androidx.media2:media2-common:1.0.0-rc01 and androidx.media2:media2-widget) are actually in the same library group, androidx.media2, it seems like lint tool cannot detect it properly..?

Alan, is it a known issue? Would it be okay if we bypass this lint errors?

Patch-set: 1
Reviewer: Gerrit User 1044446 <1044446@85c56323-6fa9-3386-8a01-6480fb634889>
Reviewer: Gerrit User 1018419 <1018419@85c56323-6fa9-3386-8a01-6480fb634889>