Update patch set 13
Patch Set 13:

Does this error mean that we cannot add a method? I can see that it breaks compat if we add an abstract method to an abstract class or inerface, but this is an annotation.

/home/yaraki/src/androidx-master-dev/frameworks/support/room/common/src/main/java/androidx/room/ColumnInfo.java:76: error: Added method androidx.room.ColumnInfo.defaultValue() [AddedAbstractMethod]

Patch-set: 13
Reviewer: Gerrit User 1051900 <1051900@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Presubmit-Ready=0