Update patch set 2
Patch Set 2:

Looks like a legit failure. Host side tests don't need size annotations, so we could just remove them.

dev/frameworks/support/recyclerview/recyclerview/src/test/java/androidx/recyclerview/widget/BatchingListUpdateCallbackTest.java:22: error: package androidx.test.filters does not exist
import androidx.test.filters.SmallTest;
^
/usr/local/google/buildbot/src/android/androidx-master-dev/frameworks/support/recyclerview/recyclerview/src/test/java/androidx/recyclerview/widget/BatchingListUpdateCallbackTest.java:30: error: cannot find symbol
@SmallTest
^
symbol: class SmallTest
/usr/local/google/buildbot/src/android/androidx-master-dev/frameworks/support/recyclerview/recyclerview/src/test/java/androidx/recyclerview/widget/ViewInfoStoreTest.java:38: error: package androidx.test.filters does not exist
import androidx.test.filters.SmallTest;
^
/usr/local/google/buildbot/src/android/androidx-master-dev/frameworks/support/recyclerview/recyclerview/src/test/java/androidx/recyclerview/widget/ViewInfoStoreTest.java:52: error: cannot find symbol
@SmallTest
^
symbol: class SmallTest
/usr/local/google/buildbot/src/android/androidx-master-dev/frameworks/support/recyclerview/recyclerview/src/test/java/androidx/recyclerview/widget/SortedListTest.java:29: error: package androidx.test.filters does not exist
import androidx.test.filters.SmallTest;
^
/usr/local/google/buildbot/src/android/androidx-master-dev/frameworks/support/recyclerview/recyclerview/src/test/java/androidx/recyclerview/widget/SortedListTest.java:48: error: cannot find symbol
@SmallTest
^
symbol: class SmallTest
/usr/local/google/buildbot/src/android/androidx-master-dev/frameworks/support/recyclerview/recyclerview/src/test/java/androidx/recyclerview/widget/OpReorderTest.java:30: error: package androidx.test.filters does not exist
import androidx.test.filters.SmallTest;
^
/usr/local/google/buildbot/src/android/androidx-master-dev/frameworks/support/recyclerview/recyclerview/src/test/java/androidx/recyclerview/widget/OpReorderTest.java:44: error: cannot find symbol
@SmallTest
^
symbol: class SmallTest
/usr/local/google/buildbot/src/android/androidx-master-dev/frameworks/support/recyclerview/recyclerview/src/test/java/androidx/recyclerview/widget/SortedListBatchedCallbackTest.java:23: error: package androidx.test.filters does not exist
import androidx.test.filters.SmallTest;
^
/usr/local/google/buildbot/src/android/androidx-master-dev/frameworks/support/recyclerview/recyclerview/src/test/java/androidx/recyclerview/widget/SortedListBatchedCallbackTest.java:33: error: cannot find symbol
@SmallTest
^
symbol: class SmallTest
/usr/local/google/buildbot/src/android/androidx-master-dev/frameworks/support/recyclerview/recyclerview/src/test/java/androidx/recyclerview/widget/DiffUtilTest.java:27: error: package androidx.test.filters does not exist
import androidx.test.filters.SmallTest;
^
/usr/local/google/buildbot/src/android/androidx-master-dev/frameworks/support/recyclerview/recyclerview/src/test/java/androidx/recyclerview/widget/DiffUtilTest.java:44: error: cannot find symbol
@SmallTest
^
symbol: class SmallTest
/usr/local/google/buildbot/src/android/androidx-master-dev/frameworks/support/recyclerview/recyclerview/src/test/java/androidx/recyclerview/widget/AdapterHelperTest.java:27: error: package androidx.test.filters does not exist
import androidx.test.filters.SmallTest;
^
/usr/local/google/buildbot/src/android/androidx-master-dev/frameworks/support/recyclerview/recyclerview/src/test/java/androidx/recyclerview/widget/AdapterHelperTest.java:46: error: cannot find symbol
@SmallTest
^
symbol: class SmallTest
14 errors

Patch-set: 2
Reviewer: Gerrit User 1086749 <1086749@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Presubmit-Ready=0