Update patch set 2
Patch Set 2:

> Patch Set 2:
> 
> > Patch Set 2:
> > 
> > Ashley, any idea what does this translate to? :)
> > 
> > So no more abstract methods? Then how are we going to add more types support?
> > Thanks.
> > 
> > /usr/local/google/home/tonymak/android/androidx-master-dev/frameworks/support/versionedparcelable/src/main/java/androidx/versionedparcelable/VersionedParcel.java:209: error: Added method androidx.versionedparcelable.VersionedParcel.readLongObject() [AddedAbstractMethod]
> > /usr/local/google/home/tonymak/android/androidx-master-dev/frameworks/support/versionedparcelable/src/main/java/androidx/versionedparcelable/VersionedParcel.java:142: error: Added method androidx.versionedparcelable.VersionedParcel.writeLongObject(Long) [AddedAbstractMethod]
> > Aborting: Found compatibility problems checking the public API against the API in /usr/local/google/home/tonymak/android/androidx-master-dev/frameworks/support/versionedparcelable/api/restricted_1.0.0.txt
> 
> We'll need a version bump for this, and ideally, I'd want to refactor the reading/writing code at the same time. I'll get back to you on an approach today or tomorrow.

It sounds like a version bump will get pretty thorny, since core depends on versionedparcelable. Is there a way you can work around the lack of boxed types for now?

Patch-set: 2
Reviewer: Gerrit User 1345241 <1345241@85c56323-6fa9-3386-8a01-6480fb634889>