Create patch set 2
Patch Set 2: Commit message was updated.

Patch-set: 2
Patch-set-description: Edit commit message
Subject: DO NOT MERGE - Fix NoClassDefFoundError caused by CallbackToFutureAdapter
Commit: 6256177be0f04c9f312d9a0e1d3502ab5dddbb3e
Tag: autogenerated:gerrit:newPatchSet
Groups: 4bb9079ff9e263add49f2c43b874ca5be4ddfc9f