DO NOT SUBMIT: Repro compose compiler bug
This code is invalid and should not compile, but instead of showing an
error, it crashes with:

java.lang.IllegalStateException: Backend Internal error: Exception during code generation

Change-Id: I72e9e5912bef0ddb9c60fada0f1b38761e1e0a5d