Update patch set 1
Patch Set 1:

nick, sergey; any reason why this would fail?
it works fine on the paging branch checkout.
the only difference is the LibraryVersions change that is not included in this CL since master is further ahead.
these are the errors i receive:
/home/yboyar/src/androidx-master-dev/frameworks/support/paging/common/api/2.1.0-rc01.txt:24: error: Removed constructor androidx.paging.ItemKeyedDataSource() [RemovedMethod]
/home/yboyar/src/androidx-master-dev/frameworks/support/paging/common/api/2.1.0-rc01.txt:57: error: Removed constructor androidx.paging.PageKeyedDataSource() [RemovedMethod]
/home/yboyar/src/androidx-master-dev/frameworks/support/paging/common/src/main/java/androidx/paging/PagedList.java:621: error: Attempted to change method return from @NonNull to @Nullable: incompatible change for method androidx.paging.PagedList.get(int) [InvalidNullConversion]
/home/yboyar/src/androidx-master-dev/frameworks/support/paging/common/src/main/java/androidx/paging/PagedList.java:855: error: Attempted to change method return from @NonNull to @Nullable: incompatible change for method androidx.paging.PagedList.getLastKey() [InvalidNullConversion]
/home/yboyar/src/androidx-master-dev/frameworks/support/paging/common/api/2.1.0-rc01.txt:149: error: Removed constructor androidx.paging.PositionalDataSource() [RemovedMethod]
Aborting: Found compatibility problems checking the public API against the API in /home/yboyar/src/androidx-master-dev/frameworks/support/paging/common/api/2.1.0-rc01.txt


thereare some diffs between beta01 and rc01 though which i do not expect. will investigate.

Patch-set: 1
Reviewer: Gerrit User 1060337 <1060337@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Presubmit-Ready=0