Update patch set 5
Patch Set 5:

You need to resolve Lint errors.

/usr/local/google/buildbot/src/android/androidx-master-dev/frameworks/support/media-widget/src/main/java/androidx/media/widget/MediaControlView2.java:2552: Error: Access to private method removeCustomSpeedFromList of class MediaControlView2 requires synthetic accessor [SyntheticAccessor]
removeCustomSpeedFromList();
~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/google/buildbot/src/android/androidx-master-dev/frameworks/support/media-widget/src/main/java/androidx/media/widget/MediaControlView2.java:2558: Error: Access to private method updateSelectedSpeed of class MediaControlView2 requires synthetic accessor [SyntheticAccessor]
updateSelectedSpeed(i, mPlaybackSpeedTextList.get(i));
~~~~~~~~~~~~~~~~~~~
/usr/local/google/buildbot/src/android/androidx-master-dev/frameworks/support/media-widget/src/main/java/androidx/media/widget/MediaControlView2.java:2571: Error: Access to private method updateSelectedSpeed of class MediaControlView2 requires synthetic accessor [SyntheticAccessor]
updateSelectedSpeed(i, customSpeedText);
~~~~~~~~~~~~~~~~~~~
/usr/local/google/buildbot/src/android/androidx-master-dev/frameworks/support/media-widget/src/main/java/androidx/media/widget/MediaControlView2.java:2580: Error: Access to private method updateSelectedSpeed of class MediaControlView2 requires synthetic accessor [SyntheticAccessor]
updateSelectedSpeed(i + 1, customSpeedText);
~~~~~~~~~~~~~~~~~~~

Patch-set: 5
Reviewer: Gerrit User 1018419 <1018419@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Presubmit-Ready=0