Create change
Uploaded patch set 1.

Patch-set: 1
Change-id: I64588ec84b1a452a5ceae40a1ca6fab4c476c11a
Subject: Fix ATP timeout due to NoClassDefFoundError which is caused by CallbackToFutureAdapter class not found.
Branch: refs/heads/androidx-master-dev
Status: new
Topic: 
Commit: 33b2ce8dff3ba48ad4651bc8f876c446534fbbbd
Tag: autogenerated:gerrit:newPatchSet
Groups: 33b2ce8dff3ba48ad4651bc8f876c446534fbbbd
Private: false
Work-in-progress: false